In [24]:
import pandas as pd
import numpy as np
import os

In [25]:
INPUT_PATH = "../../data_lake/ml/datasets/df_validation.parquet"
OUTPUT_PATH = "../../data_lake/ml/datasets/df_features.parquet"

In [58]:
os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

df = pd.read_parquet(INPUT_PATH)

In [59]:
df

,order_id,is_late_delivery,price,freight_value,total_item_value,product_weight_g,product_volume_cm3,product_category_name,seller_state,customer_state,seller_city,customer_city,seller_zip_code_prefix,customer_zip_code_prefix,purchase_ts,seller_avg_lat,seller_avg_lng,purchase_ts_1,customer_avg_lat,customer_avg_lng
0,3a6d41a4fe7a8e841b7c8e4b77d4e301,0,53.99,15.13,69.12,200.0,3328.0,perfumaria,SP,ES,santo andre,cachoeiro de itapemirim,09015,29311,2017-11-24 11:29:52,-23.659276,-46.523244,2017-11-24 11:29:52,-20.845737,-41.144435
1,f07b0af882cdeef616def36fd78fbb23,0,239.90,16.43,256.33,335.0,2992.0,relogios_presentes,SP,RJ,sumare,paraiba do sul,13170,25850,2017-07-16 19:20:47,-22.821766,-47.270344,2017-07-16 19:20:47,-22.164713,-43.292192
2,26691e37091554c74df671ce610ead4c,0,116.90,16.58,133.48,1750.0,4500.0,cama_mesa_banho,SP,MG,ibitinga,uberlandia,14940,38400,2017-11-24 21:07:00,-21.757321,-48.829744,2017-11-24 21:07:00,-18.913314,-48.278515
3,75559e14f308f4ff08427c567ae0a370,1,138.00,13.99,151.99,1200.0,11907.0,esporte_lazer,SP,SP,guara,santos,14580,11045,2018-02-12 13:53:31,-20.432223,-47.823949,2018-02-12 13:53:31,-23.969746,-46.321939
4,42be6028bdacb5416ab5bd400589b0a3,0,79.90,18.36,98.26,1550.0,7400.0,moveis_decoracao,PR,SP,curitiba,santo andre,80330,09061,2018-08-07 22:40:33,-25.469974,-49.307372,2018-08-07 22:40:33,-23.650543,-46.559142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95632,9e90b00b6d923fe64fa53888a5643760,0,175.90,14.21,190.11,800.0,4576.0,informatica_acessorios,SP,BA,sao jose dos campos,salvador,12230,41810,2017-05-31 21:19:45,-23.224501,-45.887771,2017-05-31 21:19:45,-12.992588,-38.453968
95633,4c480567d1db63cffddc552638c35d8f,0,79.90,10.29,90.19,1825.0,20944.0,cama_mesa_banho,SP,SP,ibitinga,pauliceia,14940,17990,2018-08-04 19:48:47,-21.757321,-48.829744,2018-08-04 19:48:47,-21.311072,-51.834520
95634,637617b3ffe9e2f7a2411243829226d0,0,79.90,24.01,103.91,8500.0,50625.0,bebes,SP,SC,sao jose do rio preto,celso ramos,15025,88598,2018-04-17 21:08:59,-20.806771,-49.389081,2018-04-17 21:08:59,-27.633202,-51.337240
95635,637617b3ffe9e2f7a2411243829226d0,0,79.90,24.01,103.91,7450.0,50625.0,bebes,SP,SC,sao jose do rio preto,celso ramos,15025,88598,2018-04-17 21:08:59,-20.806771,-49.389081,2018-04-17 21:08:59,-27.633202,-51.337240
95636,637617b3ffe9e2f7a2411243829226d0,0,79.90,24.01,103.91,7900.0,50625.0,bebes,SP,SC,sao jose do rio preto,celso ramos,15025,88598,2018-04-17 21:08:59,-20.806771,-49.389081,2018-04-17 21:08:59,-27.633202,-51.337240

In [60]:
df["purchase_month"] = df["purchase_ts"].dt.month
df["purchase_weekday"] = df["purchase_ts"].dt.weekday

In [61]:
df["log_price"] = np.log1p(df["price"])
df["log_freight"] = np.log1p(df["freight_value"])
df["log_weight"] = np.log1p(df["product_weight_g"])
df["log_volume"] = np.log1p(df["product_volume_cm3"])

In [62]:
df["freight_ratio"] = df["freight_value"] / (df["price"] + 1)

In [63]:
df

,order_id,is_late_delivery,price,freight_value,total_item_value,product_weight_g,product_volume_cm3,product_category_name,seller_state,customer_state,...,purchase_ts_1,customer_avg_lat,customer_avg_lng,purchase_month,purchase_weekday,log_price,log_freight,log_weight,log_volume,freight_ratio
0,3a6d41a4fe7a8e841b7c8e4b77d4e301,0,53.99,15.13,69.12,200.0,3328.0,perfumaria,SP,ES,...,2017-11-24 11:29:52,-20.845737,-41.144435,11,4,4.007151,2.780681,5.303305,8.110427,0.275141
1,f07b0af882cdeef616def36fd78fbb23,0,239.90,16.43,256.33,335.0,2992.0,relogios_presentes,SP,RJ,...,2017-07-16 19:20:47,-22.164713,-43.292192,7,6,5.484382,2.858193,5.817111,8.004032,0.068203
2,26691e37091554c74df671ce610ead4c,0,116.90,16.58,133.48,1750.0,4500.0,cama_mesa_banho,SP,MG,...,2017-11-24 21:07:00,-18.913314,-48.278515,11,4,4.769837,2.866762,7.467942,8.412055,0.140628
3,75559e14f308f4ff08427c567ae0a370,1,138.00,13.99,151.99,1200.0,11907.0,esporte_lazer,SP,SP,...,2018-02-12 13:53:31,-23.969746,-46.321939,2,0,4.934474,2.707383,7.090910,9.384966,0.100647
4,42be6028bdacb5416ab5bd400589b0a3,0,79.90,18.36,98.26,1550.0,7400.0,moveis_decoracao,PR,SP,...,2018-08-07 22:40:33,-23.650543,-46.559142,8,1,4.393214,2.963209,7.346655,8.909370,0.226947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95632,9e90b00b6d923fe64fa53888a5643760,0,175.90,14.21,190.11,800.0,4576.0,informatica_acessorios,SP,BA,...,2017-05-31 21:19:45,-12.992588,-38.453968,5,2,5.175585,2.721953,6.685861,8.428799,0.080328
95633,4c480567d1db63cffddc552638c35d8f,0,79.90,10.29,90.19,1825.0,20944.0,cama_mesa_banho,SP,SP,...,2018-08-04 19:48:47,-21.311072,-51.834520,8,5,4.393214,2.423917,7.509883,9.949655,0.127194
95634,637617b3ffe9e2f7a2411243829226d0,0,79.90,24.01,103.91,8500.0,50625.0,bebes,SP,SC,...,2018-04-17 21:08:59,-27.633202,-51.337240,4,1,4.393214,3.219276,9.047939,10.832221,0.296786
95635,637617b3ffe9e2f7a2411243829226d0,0,79.90,24.01,103.91,7450.0,50625.0,bebes,SP,SC,...,2018-04-17 21:08:59,-27.633202,-51.337240,4,1,4.393214,3.219276,8.916104,10.832221,0.296786
95636,637617b3ffe9e2f7a2411243829226d0,0,79.90,24.01,103.91,7900.0,50625.0,bebes,SP,SC,...,2018-04-17 21:08:59,-27.633202,-51.337240,4,1,4.393214,3.219276,8.974745,10.832221,0.296786

In [64]:
df.describe()

,is_late_delivery,price,freight_value,total_item_value,product_weight_g,product_volume_cm3,purchase_ts,seller_avg_lat,seller_avg_lng,purchase_ts_1,customer_avg_lat,customer_avg_lng,purchase_month,purchase_weekday,log_price,log_freight,log_weight,log_volume,freight_ratio
count,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637,95637.000000,95637.000000,95637,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000
mean,0.079687,123.078333,20.005978,143.084311,2050.158495,14930.475747,2018-01-02 22:24:34.117381,-22.797276,-47.253325,2018-01-02 22:24:34.117381,-21.203167,-46.183118,6.033983,2.757887,4.362644,2.893909,6.682375,8.829998,0.300082
min,0.000000,0.850000,0.000000,6.080000,0.000000,168.000000,2016-09-15 12:16:38,-32.079231,-63.893565,2016-09-15 12:16:38,-33.690246,-72.668881,1.000000,0.000000,0.615186,0.000000,0.000000,5.129899,0.000000
25%,0.000000,40.000000,13.100000,56.850000,300.000000,2808.000000,2017-09-15 18:48:53,-23.612642,-48.829744,2017-09-15 18:48:53,-23.589383,-48.102420,3.000000,1.000000,3.713572,2.646175,5.707110,7.940584,0.130719
50%,0.000000,78.000000,16.320000,94.400000,700.000000,6336.000000,2018-01-22 00:15:05,-23.419362,-46.755690,2018-01-22 00:15:05,-22.924504,-46.631469,6.000000,3.000000,4.369448,2.851862,6.552508,8.754161,0.221290
75%,0.000000,139.000000,21.160000,161.080000,1800.000000,18144.000000,2018-05-06 20:37:58,-21.757321,-46.523244,2018-05-06 20:37:58,-20.140617,-43.625086,8.000000,4.000000,4.941642,3.098289,7.496097,9.806150,0.373265
max,1.000000,6735.000000,409.680000,6929.310000,40425.000000,294000.000000,2018-08-29 15:00:37,-2.500251,-34.855658,2018-08-29 15:00:37,42.184003,-8.723762,12.000000,6.000000,8.815222,6.017814,10.607228,12.591338,12.054054
std,0.270809,186.289133,15.664356,193.339859,3650.442980,22802.480971,NaN,2.743620,2.343186,NaN,5.592758,4.049103,3.226668,1.968431,0.900754,0.523899,1.322550,1.281851,0.283727

In [65]:
df = pd.get_dummies(
    df,
    columns=["product_category_name"],
    drop_first=True,
    dtype=int
)

In [66]:
df.drop(columns=["order_id","price","freight_value","total_item_value","product_weight_g","product_volume_cm3","purchase_ts","purchase_ts_1"], inplace=True)

In [67]:
df["route"] = (
    df["seller_state"] +
    "_" +
    df["customer_state"]
)

In [71]:
route_analysis = (
    df.groupby("distance_km")
      .agg(
          atraso=('is_late_delivery','mean'),
          volume=('is_late_delivery','count')
      )
      .sort_values('volume', ascending=False)
)

print(route_analysis.head(30))

               atraso  volume
distance_km
0.000000     0.090909      22
10.536872    0.000000      15
680.765823   0.133333      15
247.519685   0.000000      14
699.922242   0.071429      14
574.634514   0.384615      13
242.411526   0.000000      11
353.764441   0.100000      10
581.092998   0.000000      10
626.789428   0.000000      10
576.028998   0.300000      10
340.356579   0.100000      10
343.033000   0.000000       9
568.881523   0.111111       9
544.118230   0.000000       9
1164.898854  0.000000       9
541.017478   0.125000       8
537.803292   0.125000       8
555.956290   0.250000       8
222.722314   0.000000       8
151.921837   0.000000       8
219.592525   0.000000       8
729.318034   0.125000       8
574.068190   0.125000       8
536.752107   0.375000       8
285.645283   0.125000       8
575.928346   0.250000       8
806.405765   0.000000       8
588.882421   0.500000       8
900.085749   0.125000       8

In [48]:
df = pd.get_dummies(
    df,
    columns=["route"],
    drop_first=True,
    dtype=int
)

In [69]:
import numpy as np

def haversine(lat1, lon1, lat2, lon2):

    R = 6371  # km

    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)

    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        np.sin(dlat / 2) ** 2
        + np.cos(lat1)
        * np.cos(lat2)
        * np.sin(dlon / 2) ** 2
    )

    c = 2 * np.arcsin(np.sqrt(a))

    return R * c

In [70]:
df["distance_km"] = haversine(
    df["customer_avg_lat"],
    df["customer_avg_lng"],
    df["seller_avg_lat"],
    df["seller_avg_lng"]
)

In [72]:
df["distance_km"].value_counts()

distance_km
0.000000       22
680.765823     15
10.536872      15
247.519685     14
699.922242     14
               ..
574.184145      1
1335.998671     1
22.077897       1
877.160896      1
929.021367      1
Name: count, Length: 87690, dtype: int64

In [53]:
df.drop(columns=["seller_state","customer_state","seller_city","customer_city","seller_zip_code_prefix","customer_zip_code_prefix","seller_avg_lat","seller_avg_lng","customer_avg_lat","customer_avg_lng"], inplace=True)

In [56]:
df.describe()

,is_late_delivery,purchase_month,purchase_weekday,log_price,log_freight,log_weight,log_volume,freight_ratio,product_category_name_alimentos,product_category_name_alimentos_bebidas,...,route_SP_RJ,route_SP_RN,route_SP_RO,route_SP_RR,route_SP_RS,route_SP_SC,route_SP_SE,route_SP_SP,route_SP_TO,distance_km
count,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,...,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000,95637.000000
mean,0.079687,6.033983,2.757887,4.362644,2.893909,6.682375,8.829998,0.300082,0.004413,0.002290,...,0.084612,0.003451,0.001694,0.000293,0.036900,0.023568,0.002112,0.319019,0.002039,600.501154
std,0.270809,3.226668,1.968431,0.900754,0.523899,1.322550,1.281851,0.283727,0.066280,0.047798,...,0.278304,0.058640,0.041122,0.017108,0.188517,0.151701,0.045910,0.466099,0.045109,592.863189
min,0.000000,1.000000,0.000000,0.615186,0.000000,0.000000,5.129899,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,3.000000,1.000000,3.713572,2.646175,5.707110,7.940584,0.130719,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,189.026710
50%,0.000000,6.000000,3.000000,4.369448,2.851862,6.552508,8.754161,0.221290,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,434.436306
75%,0.000000,8.000000,4.000000,4.941642,3.098289,7.496097,9.806150,0.373265,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,797.737235
max,1.000000,12.000000,6.000000,8.815222,6.017814,10.607228,12.591338,12.054054,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,8677.912290

In [57]:
df.to_parquet(OUTPUT_PATH, index=False)